services:
  plate-checker-api:
    build: .
    ports:
      - "5555:5555"
    environment:
      - FLASK_ENV=production
      - PORT=5555
    restart: unless-stopped
    container_name: indonesian-plate-checker